:- include('grammar.pl').
%%:- include('lpi_caw_commands.pl').
:- include('listprologinterpreter1listrecursion4.pl').
:- include('listprologinterpreter3preds5.pl').
:- include('lpiverify4.pl').
:- include('lpiverify4_open.pl').
:- include('lpiverify4_types.pl').
:- include('lpiverify4_open_types.pl').
%%:- include('caw5 copy 12.pl').
%%:- include('cawpverify.pl').
%%:- include('rcawp.pl').
%%:- include('rcaw.pl').
%%:- include('texttobr2.pl').
:- include('la_strings.pl').
%:- include('../Languages/lang_db_generator.pl').
:- include('lpiverify4-fr.pl').
:- include('operators.pl').
:- include('lpiverify4_test_lang_all.pl').
:- include('../Languages/make_docs.pl').
