%% Meditation.pl

%% lucian, green, friendliness, medicine, sutras, courses, qi gong and yoga mantras and sutras - arem 10 br links
%% Stops linking in meditators 100 years after date of learning LM

%%:- include('qb2.pl').
:- include('listprolog').
:- include('texttobr').
:- include('texttobr2qb').
%%:- include('texttobrqb').
:- include('la_strings').
:- include('mergetexttobrdict').
:- include('edit.pl').
:- include('meditatorsanddoctors').

%% 14 5 19 - 250 for dot, point or utterance instance

meditation :-
	%%File="I love you, I love you, I love you.  Arem.",
	%% dailyregimen,noheadachesapp,nobodyproblemsapp,arem
	DotsandUtterances is 4*80, %% With radio button for graciously give or blame and graciously give or blame
	texttobr2(DotsandUtterances), %% arem
	texttobr2(DotsandUtterances), %% lucian
	texttobr2(DotsandUtterances), %% green
	texttobr2(DotsandUtterances), %% yoga
	texttobr2(DotsandUtterances), %% dao
	Utterances1=[%%dailyregimen and noheadaches,
	nothing_rather_than_something,to_lucian,to_god,to_lecturer,today,tomorrow,day_after_tomorrow,a,b,b_to_b,seen_as_version,high_quality_version,army_go,army_return,
		no_digestive_system_pops_from_practising_the_sutra,
first_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_protector_from_headache_in_meditation_after_honours_study,
second_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_protector_from_headache_in_meditation_after_honours_study,
first_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_no_headache,
second_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_no_headache,
first_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_turn_off_workload_from_all_employees_including_you_below_you,
second_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_turn_off_workload_from_all_employees_including_you_below_you,
lecturer_training,
recordings_training,
prepare_the_radio_button_accredited__at_the_time__turned_off_openbracket_to_make_accreditation_acceptable_closebracket_computer_science__breathsoned__vocational_education_and_training__sales__education_for_the_following,
seen_as_breasoning_out_text_before_texttobr__computer_housing_the_breasonings__70_breasonings_per_waking_hour_for_16_hours__stopping_at_midnight__no_medical_problems_from_it,
put_through_prepared_radio_button,
put_through_250_word_breasonings_from_job_medicine_to_start_the_spiritual_breasoning_process,
turn_off_mistakes,
turn_off_breasonings,
first_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_detect_and_turn_off_workloads_using_manager_algorithm,
second_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_detect_and_turn_off_workloads_using_manager_algorithm,
first_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_detect_and_turn_off_workloads_using_manager_network,
second_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_detect_and_turn_off_workloads_using_manager_network,first_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_no_muscle_aches/pains,
second_radio_button_put_on_recordings_put_through_with_pray_nut_and_bolt_quantum_box_prayer_for_no_muscle_aches/pains],
	Utterances2=[fifty_As_per_organ,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_heart,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_heart_muscles,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_continually_circulating_blood_around_the_body,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_knowing_your_heart_is_working_because_you_can_feel_your_heart_beat,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_feeling_the_blood_at_your_pulse,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_pumping_blood_containing_new_oxygen_to_every_part_of_your_body,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_pumping_the_old_blood_without_oxygen_back_through_the_lungs_where_it_picks_up_new_oxygen_to_repeat_this_cycle,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_heart_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_heart_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_heart_muscles_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_continually_circulating_blood_around_the_body_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_knowing_your_heart_is_working_because_you_can_feel_your_heart_beat_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_feeling_the_blood_at_your_pulse_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_pumping_blood_containing_new_oxygen_to_every_part_of_your_body_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_pumping_the_old_blood_without_oxygen_back_through_the_lungs_where_it_picks_up_new_oxygen_to_repeat_this_cycle_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_heart_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_lungs,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_breathing,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_oxygen_from_the_air_through_tiny_vessels_into_the_blood,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_carrying_oxygen_to_the_heart_to_be_pumped_round_your_body,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_carbon_dioxide_from_your_body_when_you_breathe_out,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_lungs_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_lungs_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_breathing_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_oxygen_from_the_air_through_tiny_vessels_into_the_blood_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_carrying_oxygen_to_the_heart_to_be_pumped_round_your_body_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_carbon_dioxide_from_your_body_when_you_breathe_out_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_lungs_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_liver,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_the_blood,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_chemicals_and_impurities,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_including_from_drugs_and_medications,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_making_and_processes_many_body_fats_and_the_liver_regrowing,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_liver_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_liver_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_the_blood_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_chemicals_and_impurities_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_including_from_drugs_and_medications_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_making_and_processes_many_body_fats_and_the_liver_regrowing_should_be_kept_going_and_not_have_blocks_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_liver_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_kidneys,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_kidneys_filtering,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_some_drugs_and_filtering_waste_products_that_leave_the_body_as_urine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_kidneys_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_kidneys_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_kidneys_filtering_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_filtering_some_drugs_and_filtering_waste_products_that_leave_the_body_as_urine_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_kidneys_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_stomach_and_intestines,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_starting_to_break_down_and_process_food__drink_and_oral_medications_in_the_body_and_absorbing_nutrients_and_drugs_through_the_stomach_and_small_intestine_walls,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_stomach_and_intestines_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_stomach_and_intestines_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_starting_to_break_down_and_process_food__drink_and_oral_medications_in_the_body_and_absorbing_nutrients_and_drugs_through_the_stomach_and_small_intestine_walls_should_be_kept_going_and_not_have_blocks_,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_stomach_and_intestines_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_thymus,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_developing_cdfour_cells_and_other_white_blood_cells,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_thymus_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_thymus_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_developing_cdfour_cells_and_other_white_blood_cells_should_be_kept_going_and_not_have_blocks_,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_thymus_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_pancreas,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_releasing_digestive_enzymes_into_the_small_intestine_and_hormones_that_control_sugar_levels_in_your_blood,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_in_that_case__living_without_a_pancreas_by_taking_insulin_to_regulate_blood_sugar_levels_and_taking_supplementary_digestive_enzymes,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_pancreas_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_pancreas_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_releasing_digestive_enzymes_into_the_small_intestine_and_hormones_that_control_sugar_levels_in_your_blood,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_in_that_case__living_without_a_pancreas_by_taking_insulin_to_regulate_blood_sugar_levels_and_taking_supplementary_digestive_enzymes_should_be_kept_going_and_not_have_blocks_,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_pancreas_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_skin,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_stopping_your_body_from_drying_out_and_being_the_main_barrier_against_infection,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_skin_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_skin_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_stopping_your_body_from_drying_out_and_being_the_main_barrier_against_infection_should_be_kept_going_and_not_have_blocks_,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_skin_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_bones,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_onezero_percent_of_bone_being_replaced_each_year,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_bones_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_bones_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_onezero_percent_of_bone_being_replaced_each_year_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_bones_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_bone_marrow,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_blood_cells_originally_coming_from_bone_marrow,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_bone_marrow_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_bone_marrow_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_blood_cells_originally_coming_from_bone_marrow_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_bone_marrow_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_blood,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_blood_pumped_by_your_heart,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_delivering_oxygen_and_nutrients_to_every_part_of_your_body_and_carrying_waste_products_away,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_blood_cells_openbracket_red_cells__white_cells__platelets_etc_closebracket_and_plasma,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_blood_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_blood_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_blood_pumped_by_your_heart_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_delivering_oxygen_and_nutrients_to_every_part_of_your_body_and_carrying_waste_products_away_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_blood_cells_openbracket_red_cells__white_cells__platelets_etc_closebracket_and_plasma_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_blood_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_plasma,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_its_nutrients__sugars__proteins__minerals__enzymes__and_other_substances_but_with_the_blood_cells_taken_out,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_plasma_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_plasma_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_its_nutrients__sugars__proteins__minerals__enzymes__and_other_substances_but_with_the_blood_cells_taken_out_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_plasma_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_lymph,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_its_white_blood_cells_and_antibodies,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_lymph_vessels__nodes__and_organs_and_removing_waste_products_from_the_body,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_lymph_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_lymph_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_its_white_blood_cells_and_antibodies_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_lymph_vessels__nodes__and_organs_and_removing_waste_products_from_the_body_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_lymph_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_lymph_nodes,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_cdfour_cells_in_your_body_resting_and_reproducing_in_your_lymph_nodes,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_lymph_nodes_function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_lymph_nodes,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_the_cdfour_cells_in_your_body_resting_and_reproducing_in_your_lymph_nodes,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_lymph_nodes_medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_organs__function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_organs__medicine,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_heart_does_not_beat_unless_your_brain_and_nervous_system_tell_it_to_do_so,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_heart_beating_because_your_brain_and_nervous_system_tell_it_to_do_so_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_skeletal_system_relies_on_the_nutrients_it_gains_from_your_digestive_system_to_build_strong__healthy_bones,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_skeletal_system_relying_on_the_nutrients_it_gains_from_your_digestive_system_to_build_strong__healthy_bones_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_cardiovascular_system_works_to_circulate_your_blood,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_cardiovascular_system_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_respiratory_system_introduces_oxygen_into_your_body,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_respiratory_system_introducing_oxygen_into_your_body_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_heart_pumping_blood_through_a_complex_network_of_blood_vessels__your_blood_circulating_through_your_digestive_system_and_picking_up_nutrients_your_body_absorbed_from_your_last_meal__your_blood_carrying_oxygen_inhaled_by_the_lungs__your_circulatory_system_delivering_oxygen_and_nutrients_to_the_other_cells_of_your_body_picking_up_any_waste_products_created_by_these_cells_including_carbon_dioxide__and_delivering_these_waste_products_to_the_kidneys_and_lungs_for_disposal_and_the_circulatory_system_carrying_hormones_from_the_endocrine_system__and_the_immune_system_s_white_blood_cells_that_fight_off_infection,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_heart_pumping_blood_through_a_complex_network_of_blood_vessels__your_blood_circulating_through_your_digestive_system_and_picking_up_nutrients_your_body_absorbed_from_your_last_meal__your_blood_carrying_oxygen_inhaled_by_the_lungs__your_circulatory_system_delivering_oxygen_and_nutrients_to_the_other_cells_of_your_body_picking_up_any_waste_products_created_by_these_cells_including_carbon_dioxide__and_delivering_these_waste_products_to_the_kidneys_and_lungs_for_disposal_and_the_circulatory_system_carrying_hormones_from_the_endocrine_system__and_the_immune_system_s_white_blood_cells_that_fight_off_infection_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_respiratory_system_relying_on_your_circulatory_system_to_deliver_the_oxygen_it_gathers__the_muscles_of_your_heart_functioning_with_the_oxygen_they_receive_from_your_lungs__the_bones_of_your_skull_and_spine_protecting_your_brain_and_spinal_cord__your_brain_regulating_the_position_of_your_bones_by_controlling_your_muscles__the_circulatory_system_providing_your_brain_with_a_constant_supply_of_oxygen_rich_blood_and_your_brain_regulating_your_heart_rate_and_blood_pressure,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_respiratory_system_relying_on_your_circulatory_system_to_deliver_the_oxygen_it_gathers__the_muscles_of_your_heart_functioning_with_the_oxygen_they_receive_from_your_lungs__the_bones_of_your_skull_and_spine_protecting_your_brain_and_spinal_cord__your_brain_regulating_the_position_of_your_bones_by_controlling_your_muscles__the_circulatory_system_providing_your_brain_with_a_constant_supply_of_oxygen_rich_blood_and_your_brain_regulating_your_heart_rate_and_blood_pressure_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_skeletal_system_relying_on_your_urinary_system_to_remove_waste_produced_by_bone_cells__the_bones_of_your_skeleton_creating_structure_that_protects_your_bladder_and_other_urinary_system_organs__your_circulatory_system_delivers_oxygen_rich_blood_to_your_bones_and_your_bones_making_new_blood_cells,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_your_skeletal_system_relying_on_your_urinary_system_to_remove_waste_produced_by_bone_cells__the_bones_of_your_skeleton_creating_structure_that_protects_your_bladder_and_other_urinary_system_organs__your_circulatory_system_delivers_oxygen_rich_blood_to_your_bones_and_your_bones_making_new_blood_cells_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_working_together__these_systems_maintaining_internal_stability_and_balance__otherwise_known_as_homeostasis,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_working_together__these_systems_maintaining_internal_stability_and_balance__otherwise_known_as_homeostasis_should_be_kept_going_and_not_have_blocks,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_organ_connections__function,
quantum_box__quantum_box_for_head_of_state_for_and_quantum_box_for_no_problems_from_honours_and_beyond_for_other_organ_connections__medicine],

	%%noheadachesapp,nobodyproblemsapp,arem],
	%% initiate_utterances(File,Utterances),
	%% currentDate(Today),
	%% Today=date(Year,Month,Day),
	meditators(Meditators),
	length(Utterances1,UL1),
	length(Utterances2,UL2),
	length(Meditators,ML),
	Length2 is 2*UL1+3*UL2, %% 2 radio buttons for ul2
	%%Length3 is is DL*250*3*250,
	texttobr2(Length2),
	Length3 is 2*ML, %% Give the meditators the As with graciously give or blame, radio button for graciously give or blame
	texttobr2(Length3),
	!.%%,texttobr(Length2,u,File,u),!.
	
	/**, friendliness, medicine, 
pedagogy,breasonings,quantumbox,lucianicmeditation,lm,meditation,qigongmantra,qigongsutra, yogamantra,yogasutrachildrenh1earningjobsprotectioninjobs,headsofstate,lucianmantrapureform,lucianmantrasunsafety,maharishisutra,meditationteachersutra,movingappearances,purusha,upasanasutra,yellowgod,greensutra,bluenature,appearances,pranayama,soma,hoursprayer,fiftybreasoningspersecond,meditationindicatorlowerriskofcancerandotherdiseasesinworkersandbroadcasters,meditationindicatordecreasedstress,meditationindicatorincreasedbloodflow,meditationincreasedbrainpotential,autobiography,computationalenglish,computerscience,economics,hermeneutics,
**/
/**,metaphysics,music,plays,popology,theology, **/

	%% protect(File,Year,Month,Day,Meditators,[],Old),
	%% writeln([oldmeditators,Old]),!.
initiate_utterances(_File,[]) :- !.
initiate_utterances(File,[_Utterances|Utterances]) :-
		texttobr2(File),texttobr(File),
		initiate_utterances(File,Utterances).
protect(_File,_Year,_Month,_Day,[],Old1,Old1) :- !.
protect(File,Year1,_Month1,_Day1,[Meditator|Meditators],Old1,Old2) :-
	Meditator=[_FirstName,_LastName,_DayDOB,_MonthDOB,_YearDOB,_DayLearned,_MonthLearned,YearLearned],
	Year2 is YearLearned+101,
	(Year2=Year1->append(Old1,[Meditator],Old3);Old3=Old1),
	texttobr2(File),texttobr(File), %% Sender
	texttobr2(File),texttobr(File), %% Recipient
	
	protect(File,Year1,_Month,_Day,Meditators,Old3,Old2).
currentDate(Today) :-
    get_time(Stamp),
    stamp_date_time(Stamp,DateTime,local),
    date_time_value(date,DateTime,Today).

%% Don't add medicine doctors 6 3 19 (medicinenoreplace.pl covers them)